bind = "0.0.0.0:8000"
workers = 10
worker_class = "sync"
timeout = 60
# accesslog = "gunicorn_access.log"
errorlog = "gunicorn_error.log"
loglevel = "info"
reload = True
daemon = True
pid = "gunicorn_pid.log"